### ISSUE TITLE
"FALL_HURT_BREAK" destroys dropped items when crushed into them.

### ISSUE THREAD

**Issue by Uboaaaaa** [ThizThizzyDizzy/tree-feller#28]
The issue was found when one of the player accidentally got killed by falling leaves. Their inventory was completely lost.

During testing it seems like the falling blocks crushed into their dropped items underneath, and destroyed them. Existing items on the ground can also be destroyed by falling leaves.

Plugin version: 1.14

**Comment by ThizThizzyDizzy** [comment]
This is a bug with bukkit, combined with my attempt to hide the workaround :P

The bug: Spawning items via bukkit deletes any other items in the same spot for 40 ticks

I have a workaround by spawning the items high in the sky and teleporting them down after 40 ticks.
But that makes the items seem to not drop for 2 seconds, so I was spawning non-stackable non-pickup-able "fake" items that would despawn in 40 ticks (most of which get deleted)

I didn't realize the fake items would delete other items though

**Comment by ThizThizzyDizzy** [comment]
Fixed in v1.14.1

**Comment by Uboaaaaa** [comment]
Seems still persisting.
Game version 1.16.5 (recently updated)
Plugin version 1.14.1
Video: https://youtu.be/biQspMt1yHg

**Comment by ThizThizzyDizzy** [comment]
Confirmed

**Comment by ThizThizzyDizzy** [comment]
After further testing, it appears this is actually a vanilla feature; falling anvils (and by extension, falling blocks with damage enabled) will destroy items they land on.
I will add a note to the config
