### ISSUE TITLE
Incorrect velocity calculation for "TOWARD" and "AWAY" fall behaviours

### ISSUE THREAD

**Issue by KaktuszSok** [ThizThizzyDizzy/tree-feller#33]
The TOWARD and AWAY fall behaviours take into account the difference between the player's and the block's Y coordinates. This creates unrealistic tree toppling behaviours where the topmost blocks of a tree are projected upwards and the blocks at the cutting level are projected the furthest horizontally. In reality, it would make more sense if the delta Y was ignored. This would cause all logs to be projected with the same horizontal velocity, which is a bit closer to reality - at the very least it is less wrong than the current behaviour.

Ideally, the topmost blocks would actually be projected the furthest, so that the tree falls over in a more convincing manner. I assume this is what "NATURAL" tries to do, but it would be nice to see the blocks fall as entities. Perhaps a "FALL_NATURAL" behaviour would be appropriate in this case.
Instead of using the configured horizontal velocity, we can derive the appropriate velocity for each block as we know its position relative to the lowest affected log (leaves will need to consider the lowest log - not leaf - too). Our block's desired toppled position would be its current position relative to the lowest log, rotated 90 degrees about an axis which is the cross product of the fall direction (again, ignoring the y delta) and the vertical (up) vector.
Now that we know the place it starts and the place it's supposed to end up, its horizontal velocity is (end.x - start.x, end.z-start.z)/t, where t is the time it takes to fall from start.y to end.y. Using one of the uvast equations, we can get t:
s = u*t + 0.5*a*t^2
where s = end.y - start.y (displacement), u = 0 (initial velocity) and a = acceleration of gravity on the falling blocks, in blocks per tick per tick. t is time measured in ticks. a will be negative and s will be <= 0 as end.y will never be greater than start.y.
Now we have:
s = 0*t + 0.5*a*t^2
s = 0.5*a*t^2
t^2 = s / (0.5*a)
t = sqrt(s / 0.5*a)
which means finally our block's horizontal velocity is:
(end.x - start.x, end.z - start.z) / sqrt(s / 0.5*a)
where end = (block - start) rotated by 90 degrees around (cross(fallDirection, up))

If my maths is wrong please correct me. I'd really appreciate it if you tried to implement this behaviour for the 1.16 version of the plugin.
Thanks!

**Comment by ThizThizzyDizzy** [comment]
> take into account the difference between the player's and the block's Y coordinates

That's a bug; The blocks are all supposed to go in the same direction

As for the rest:
I've wanted to do this for a while, but I'm not sure how to figure out the math for it
That looks like real physics calculations, which doesn't map well into minecraft:
- MC gravity isn't constant; I'm not sure how exactly it works, but it seems a little weird: https://youtu.be/Tc1aO4-kQmQ?t=620
- There's also a strong horizontal "drag" that slows horizontal movement considerably. I'm also not sure how this works either, but it can stop most falling entities' horizontal movement in seconds

**Comment by KaktuszSok** [comment]
Hmm, true, I didn't take drag into account. That does complicate things quite a lot. I guess the options now are:
- Implement the no-drag-assumed version and, if it works well enough, leave it as is
- Same as above but exponentiate the resulting velocity slightly, mess around until it feels right
- If the above options are not working out, you should be able to pre-calculate a lookup which maps from fall height (int) to fall time (in ticks, int):
```
for(int h = 0; h <= BUILD_HEIGHT_LIMIT; h++) {
    double currHeight = h;
    double vel = 0;
    int ticks = 0;
    while(currHeight > 0) {
        vel += GRAVITY; //-0.04
        vel *= (1 - DRAG); //1 - 0.02 = 0.98
        currHeight -= vel;
        ticks++;
    }
    lookup.put(h, ticks);
}
```
This still leaves horizontal drag as a major problem, and the lookup for that would need to be 2-dimensional (horizontal distance and time to fall as inputs, required speed out) and much harder to calculate. If you need to do this, it's best to simulate it for a bunch of likely inputs, graph it in 3D and try to approximate it with some function. This would be quite a pain in the ass and not really worth it imo.

**Comment by ThizThizzyDizzy** [comment]
Did some extensive testing and found the exact formulas that describe the motion of falling blocks.
X and Z velocity are individually multiplied by `.98` every tick
Y velocity is decreased by `.04` (accelerated downwards) and then multiplied by `.98` every tick

**Comment by KaktuszSok** [comment]
So, our problem is to get the initial x and z velocity required given a desired x,y and z displacement (as described in the OP). We can generate a lookup table for the fall times by the method described in my previous comment. This reduces our problem to getting the initial velocity required to achieve a desired x and z displacement after the fall time t. Since, as you found out, x and z velocities are treated separately, we can split this 2-variable problem into two 1-variable problems and combine the results.

Taking s as displacement along the axis in question, t as the time to fall (taken from the lookup table at index start.y-end.y), and u as the initial velocity along the axis, we have:
![image](https://user-images.githubusercontent.com/12380380/121275292-a1e5af00-c8cc-11eb-9e5b-125f1adc218a.png)
That is to say,
t=0 -> s = 0
t=1 -> s = u*0.98
t=2 -> s= u*0.98 + u*.98^2
t=3 -> s= u*0.98 + u*.98^2 + u*.98^3
t=n -> s = u*.98^1 + u*.98^2 + ... + u*.98^n

Our desired value for s is end.x - start.x  (or end.z - start.z for the Z axis). We know t from the lookup table and we are looking for u.
s = u * (sum of 0.98^i for i=1 to t)
-> u = s / (sum of 0.98^i for i=1 to t)
The sum part is just a geometric series like this one:
![image](https://user-images.githubusercontent.com/12380380/121278481-f3913800-c8d2-11eb-8773-adfa9f468665.png)
Using our naming scheme, we have r = 0.98, k = i, n = t.
Therefore our final formula for u is:
u = s / ((1 - 0.98^t)/1-0.98)
-> u = s * (1-0.98) / (1 - 0.98^t)
-> u = s * 0.02 / (1 - 0.98^t)
To recap, u is velocity along axis in blocks per tick, s is end.[axis] - start.[axis] and t is fall time in blocks. The appropriate initial velocity vector is given by:
```
int t = fallTimeLookup[start.y - end.y];
Vector vel = new Vector(getAxisVelocity(end.x - start.x, t), 0, getAxisVelocity(end.z - start.z, t));

double getAxisVelocity(int s, int t) {
    return (s * 0.02d) / (1 - Math.pow(0.98, t));
}
```
Example:
start = 100,75,100
end = 100,64,111

t = fallTimeLookup[75 - 64] = fallTimeLookup[11] = 26
vel = new Vector(getAxisVelocity(100-100, t), 0, getAxisVelocity(111-100, t));
the x velocity is clearly 0 (s=0 -> 0 * 0.02d / whatever = 0)
the z velocity is:
s = 111 - 100 = 11 -> (11*0.02) / (1 - 0.98^26) = 0.22 / 0.4086... = 0.538417... blocks per tick
so vel = (0, 0, 0.538417) blocks per tick
which seems about right for a block falling 11 blocks down (and 11 blocks forward), which would take 26 ticks. With no air resistance, that would result in 13.9988 blocks travelled horizontally. I think this formula is correct.

Finally, some pseudocode for getting the end position:
```
private static final Vector UP = new Vector(0, 1, 0);
Vector getEndPosition(Vector start, Vector bottomLog, Vector fallDirection) { //fallDirection.y == 0, and fallDirection is normalised
    return start.clone().subtract(bottomLog).rotateAroundAxis(90, Vector.crossProduct(fallDirection, UP));
}
```

Hopefully this should be all that's required to get this working :)

**Comment by ThizThizzyDizzy** [comment]
Wow, that’s a lot of complicated equations, thank you :D

Does this take into account the initial vertical velocity?
(vertical-fell-velocity is still applied, though
random/directional/explosive are ignored)

Also, I implemented this yesterday, but since I didn’t know what formulas
to use, it basically guess-and-checks until it gets close enough. Probably
not very fast though.

It also doesn’t work very well because Minecraft doesn’t handle falling
blocks very well :(

**Comment by ThizThizzyDizzy** [comment]
> It also doesn’t work very well because Minecraft doesn’t handle falling blocks very well :(
To elaborate on that last point, here's a test:
https://www.youtube.com/watch?v=AdTlsUiaaY8
(This is with my guess-and-check algorithm, calculated to less than a quarter of a pixel of inaccuracy)

**Comment by KaktuszSok** [comment]
The code I sent assumes the vertical velocity is zero. You could account for this if instead of using a lookup, you calculated fall time directly (like in [my previous comment](https://github.com/ThizThizzyDizzy/tree-feller/issues/33#issuecomment-854172153)), and set vel to whatever initial value you need. If they're launched upwards, then vel should start as a negative value, since the calculation subtracts velocity from height every tick, so a positive velocity means its falling downwards.

What does it look like when the upwards velocity is zero? Also, can you send the guess-and-check algorithm?

**Comment by ThizThizzyDizzy** [comment]
the guess-and-check is [here](https://github.com/ThizThizzyDizzy/tree-feller/blob/03863fc0755ec7da5d3faea56b25a6ba0b102a52/src/com/thizthizzydizzy/treefeller/FellBehavior.java#L193)
It increments by 1 until it passes (1 b/t is usually way too fast, so that's usually one iteration)
then it pretty much uses a binary search style thing to hone in on the right answer

**Comment by KaktuszSok** [comment]
Okay, my method has slightly different inputs but I think you have the correct information to work with it anyway. Try this and see how it works.
```java
private static final double GRAVITY = 0.04d;
    private static final double DRAG = 0.02d;
    private static final Vector UP = new Vector(0, 1, 0);

    /**
     * @param b The block in question
     * @param bottomLog Bottommost log of the tree
     * @param fallDirection Normalised direction the block should fall. Y component must be zero.
     * @param yVelocity The initial y velocity this block should be given.
     * @return The velocity that should be applied to the falling block
     */
    private static Vector calculateVelocityForBlock(Block b, Block bottomLog, Vector fallDirection, double yVelocity) {
        Vector start = b.getLocation().toVector();
        Vector bottomLogPos = bottomLog.getLocation().toVector();
        Vector end = getEndPosition(start, bottomLogPos, fallDirection, yVelocity);
        return calculateInitialVelocity(start, end, yVelocity);
    }

    /**
     * Gets the position a felled block should land at given its starting position, the bottommost log of the tree, the direction it should fall and its initial upwards velocity
     * @param start Where the block is positioned before being felled
     * @param bottomLog Where the bottommost log of the tree is
     * @param fallDirection Normalised horizontal falling direction. Y component must be zero.
     * @param yVelocity The initial y velocity (upwards) this block should have
     */
    private static Vector getEndPosition(Vector start, Vector bottomLog, Vector fallDirection, double yVelocity) {
        return start.clone().subtract(bottomLog).rotateAroundAxis(fallDirection.crossProduct(UP), 90);
    }

    /**
     * @param height How far down are we falling
     * @param yVelocity The initial y velocity upwards
     * @return Ticks it takes to fall
     */
    private static int getFallTime(int height, double yVelocity) {
        double currHeight = height;
        double vel = -yVelocity;
        int ticks = 0;
        while(currHeight > 0) {
            vel += GRAVITY;
            vel *= (1 - DRAG);
            currHeight -= vel;
            ticks++;
        }
        return ticks;
    }

    /**
     * Calculates the required velocity for a felled block to land in a specific position
     * @param start Where the block starts at
     * @param end Where the block should land
     * @param yVelocity How fast upwards should the block be propelled
     * @return The velocity that should be applied to the falling block
     */
    private static Vector calculateInitialVelocity(Vector start, Vector end, double yVelocity) {
        int t = getFallTime(start.getBlockY()-end.getBlockY(), yVelocity);
        return new Vector(getAxisVelocity(end.getBlockX() - start.getBlockX(), t), 0, getAxisVelocity(end.getBlockZ() - start.getBlockZ(), t));
    }

    /**
     * Calculates the velocity required to travel a certain distance in a given time, accounting for drag
     * @param s The displacement (distance) that should be travelled along this axis
     * @param t The time that we have to travel that far
     * @return The velocity that should be applied to travel s blocks in t ticks along one axis
     */
    private static double getAxisVelocity(int s, int t) {
        return (s * 0.02d) / (1 - Math.pow(0.98, t));
    }
```
Calling the first method should give you the velocity you need.

**Comment by ThizThizzyDizzy** [comment]
I don't have the bottom log in the tree, just the Y value of it
I could get the block itself, but I'm worried what might change for larger trees where the blocks might not be aligned with the bottom log

**Comment by ThizThizzyDizzy** [comment]
Just tested it; the trees are flying off into the distance towards the world origin

**Comment by ThizThizzyDizzy** [comment]
Fixed/added in v1.16

**Comment by KaktuszSok** [comment]
Nice stuff! I tested it out, it works great when the felling animation is turned off. When it's turned on, most logs are stopped by the ones above them still not being broken - especially when facing along the north/south axis, for whatever reason. This could be solved by allowing the animation to play in order of descending y coordinate, i.e. the topmost blocks break first. Would be a nice feature since the animation looks cool. Thanks!

**Comment by ThizThizzyDizzy** [comment]
It’s a miracle it works as well as it does honestly; thanks for the code :P

Also, please make a new issue for feature requests to prevent this from getting too crowded
